% Reads in spike data from
% cellList, taking care with files that don't exist.
% (Like readSpikeData, but doesn't require a video file or position data)
% session should be a path to the original data
% cellList is a list of cells as strings, or if you have a 
% ttlist saved as a text file, use cellList = ReadFileList(ttlist)

function spikedata = readSpikeDataOnly(session,cellList)
if ischar(cellList)
    cellList = ReadFileList(cellList);
end
dirFiles = dir(session);   % Files in directory
NaFile = cell(1,length(cellList)); % Store non existing file names here
NaFileCounter = 0;          % Counts number of non-existant files
for cc=1:length(cellList)
    I = strmatch(char(cellList(cc)),char(dirFiles.name),'exact'); % Try to find file in dir
    if isempty(I) % File doesn't exist
        NaFileCounter = NaFileCounter + 1;
        NaFile(1,NaFileCounter) = cellList(cc);
    end
end
NaFile = NaFile(1,1:NaFileCounter);

% Load data from the cut files generated by Mclust
S = LoadSpikes(cellList,session,NaFile);
spikedata = {S};
